[base]
version = "1.0.0"

[server]
host = "0.0.0.0"
port = "10000"
masterAddr = ":11000"

[gateMaster]
tcpAddr = ":11000"
httpAddr = ":11001"

[gateMember]
host = "0.0.0.0"
port = "12000"
masterAddr = ":11000"